-- -------------------------------------------------------------
-- 
-- File Name: D:\zizim\Documents\UJN_HW\proj2\hdl_prj\hdlsrc\dbpsk_hdl_cosim\dbpsk_hdl_cosim\CmpZero.vhd
-- Created: 2026-06-24 13:27:05
-- 
-- Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: CmpZero
-- Source Path: dbpsk_hdl_cosim/DUT/DBPSK_Demod_HDL/CmpZero
-- Hierarchy Level: 2
-- Model version: 1.12
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY CmpZero IS
  PORT( u                                 :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        y                                 :   OUT   std_logic
        );
END CmpZero;


ARCHITECTURE rtl OF CmpZero IS

  -- Signals
  SIGNAL u_signed                         : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL Constant_out1                    : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL Compare_out1                     : std_logic;

BEGIN
  u_signed <= signed(u);

  Constant_out1 <= to_signed(16#0000#, 16);

  
  Compare_out1 <= '1' WHEN u_signed < Constant_out1 ELSE
      '0';

  y <= Compare_out1;

END rtl;

