-- -------------------------------------------------------------
-- 
-- File Name: D:\zizim\Documents\UJN_HW\proj2\hdl_prj\hdlsrc\dbpsk_hdl_cosim\dbpsk_hdl_cosim\DBPSK_Mod_HDL.vhd
-- Created: 2026-06-24 13:27:05
-- 
-- Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: DBPSK_Mod_HDL
-- Source Path: dbpsk_hdl_cosim/DUT/DBPSK_Mod_HDL
-- Hierarchy Level: 1
-- Model version: 1.12
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.DUT_pkg.ALL;

ENTITY DBPSK_Mod_HDL IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        bit_in                            :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        sym_out                           :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En14
        );
END DBPSK_Mod_HDL;


ARCHITECTURE rtl OF DBPSK_Mod_HDL IS

  -- Constants
  CONSTANT LUT_table_data                 : vector_of_signed16(0 TO 1) := 
    (to_signed(16#4000#, 16), to_signed(-16#4000#, 16));  -- sfix16 [2]

  -- Signals
  SIGNAL init_guard_true_1                : std_logic;
  SIGNAL init_guard_true_2                : std_logic;
  SIGNAL outinit_guard_default            : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL bit_in_unsigned                  : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL bit_in_is_not0                   : std_logic;
  SIGNAL Diff_Enc_XOR_out1                : std_logic;
  SIGNAL Diff_Enc_Reg_out1                : std_logic;
  SIGNAL Diff_Enc_DTConv_out1             : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL relopout_1_1                     : std_logic;
  SIGNAL prelookup_idx                    : std_logic;  -- ufix1
  SIGNAL LUT_cast                         : signed(31 DOWNTO 0);  -- int32
  SIGNAL out_rsvd                         : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL out_rsvd_1                       : signed(15 DOWNTO 0) := to_signed(16#0000#, 16);  -- sfix16_En14
  SIGNAL Delay_out1                       : signed(15 DOWNTO 0);  -- sfix16_En14

BEGIN
  init_guard_true_1 <= '1';

  matching_delays_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      init_guard_true_2 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        init_guard_true_2 <= init_guard_true_1;
      END IF;
    END IF;
  END PROCESS matching_delays_process;


  outinit_guard_default <= to_signed(16#0000#, 16);

  bit_in_unsigned <= unsigned(bit_in);

  
  bit_in_is_not0 <= '1' WHEN bit_in_unsigned /= to_unsigned(16#00#, 8) ELSE
      '0';

  Diff_Enc_Reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Diff_Enc_Reg_out1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Diff_Enc_Reg_out1 <= Diff_Enc_XOR_out1;
      END IF;
    END IF;
  END PROCESS Diff_Enc_Reg_process;


  Diff_Enc_XOR_out1 <= bit_in_is_not0 XOR Diff_Enc_Reg_out1;

  Diff_Enc_DTConv_out1 <= '0' & '0' & '0' & '0' & '0' & '0' & '0' & Diff_Enc_XOR_out1;

  
  relopout_1_1 <= '1' WHEN Diff_Enc_DTConv_out1 >= to_unsigned(16#01#, 8) ELSE
      '0';

  prelookup_idx <= relopout_1_1;

  LUT_cast <= '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & prelookup_idx;
  out_rsvd <= LUT_table_data(to_integer(LUT_cast));

  PipelineRegister_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        out_rsvd_1 <= out_rsvd;
      END IF;
    END IF;
  END PROCESS PipelineRegister_process;


  
  Delay_out1 <= outinit_guard_default WHEN init_guard_true_2 = '0' ELSE
      out_rsvd_1;

  sym_out <= std_logic_vector(Delay_out1);

END rtl;

