// -------------------------------------------------------------
// 
// File Name: D:\zizim\Documents\UJN_HW\proj2\hdl_prj\hdlsrc\dbpsk_hdl_cosim\dbpsk_hdl_cosim\DBPSK_Demod_HDL.v
// Created: 2026-06-24 13:27:37
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: DBPSK_Demod_HDL
// Source Path: dbpsk_hdl_cosim/DUT/DBPSK_Demod_HDL
// Hierarchy Level: 1
// Model version: 1.12
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module DBPSK_Demod_HDL
          (clk,
           reset,
           enb,
           rx_sym_in,
           bit_out);


  input   clk;
  input   reset;
  input   enb;
  input   signed [15:0] rx_sym_in;  // sfix16_En14
  output  [7:0] bit_out;  // uint8


  wire CmpZero_y;
  wire [7:0] DTConv_out1;  // uint8
  wire DTConv_out1_is_not0;
  wire Diff_Dec_XOR_out1;
  reg  Diff_Dec_Reg_out1;
  wire [7:0] Diff_Dec_DTConv_out1;  // uint8


  CmpZero u_CmpZero (.u(rx_sym_in),  // sfix16_En14
                     .y(CmpZero_y)
                     );

  assign DTConv_out1 = {7'b0, CmpZero_y};

  assign DTConv_out1_is_not0 = DTConv_out1 != 8'b00000000;

  always @(posedge clk or posedge reset)
    begin : Diff_Dec_Reg_process
      if (reset == 1'b1) begin
        Diff_Dec_Reg_out1 <= 1'b0;
      end
      else begin
        if (enb) begin
          Diff_Dec_Reg_out1 <= Diff_Dec_XOR_out1;
        end
      end
    end

  assign Diff_Dec_XOR_out1 = DTConv_out1_is_not0 ^ Diff_Dec_Reg_out1;

  assign Diff_Dec_DTConv_out1 = {7'b0, Diff_Dec_XOR_out1};

  assign bit_out = Diff_Dec_DTConv_out1;

endmodule  // DBPSK_Demod_HDL

