-- -------------------------------------------------------------
-- 
-- File Name: D:\zizim\Documents\UJN_HW\proj2\hdl_prj\hdlsrc\dbpsk_hdl_cosim\dbpsk_hdl_cosim\DBPSK_Demod_HDL.vhd
-- Created: 2026-06-24 13:27:05
-- 
-- Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: DBPSK_Demod_HDL
-- Source Path: dbpsk_hdl_cosim/DUT/DBPSK_Demod_HDL
-- Hierarchy Level: 1
-- Model version: 1.12
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY DBPSK_Demod_HDL IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        rx_sym_in                         :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        bit_out                           :   OUT   std_logic_vector(7 DOWNTO 0)  -- uint8
        );
END DBPSK_Demod_HDL;


ARCHITECTURE rtl OF DBPSK_Demod_HDL IS

  -- Component Declarations
  COMPONENT CmpZero
    PORT( u                               :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          y                               :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : CmpZero
    USE ENTITY work.CmpZero(rtl);

  -- Signals
  SIGNAL CmpZero_y                        : std_logic;
  SIGNAL DTConv_out1                      : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL DTConv_out1_is_not0              : std_logic;
  SIGNAL Diff_Dec_XOR_out1                : std_logic;
  SIGNAL Diff_Dec_Reg_out1                : std_logic;
  SIGNAL Diff_Dec_DTConv_out1             : unsigned(7 DOWNTO 0);  -- uint8

BEGIN
  u_CmpZero : CmpZero
    PORT MAP( u => rx_sym_in,  -- sfix16_En14
              y => CmpZero_y
              );

  DTConv_out1 <= '0' & '0' & '0' & '0' & '0' & '0' & '0' & CmpZero_y;

  
  DTConv_out1_is_not0 <= '1' WHEN DTConv_out1 /= to_unsigned(16#00#, 8) ELSE
      '0';

  Diff_Dec_Reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Diff_Dec_Reg_out1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Diff_Dec_Reg_out1 <= Diff_Dec_XOR_out1;
      END IF;
    END IF;
  END PROCESS Diff_Dec_Reg_process;


  Diff_Dec_XOR_out1 <= DTConv_out1_is_not0 XOR Diff_Dec_Reg_out1;

  Diff_Dec_DTConv_out1 <= '0' & '0' & '0' & '0' & '0' & '0' & '0' & Diff_Dec_XOR_out1;

  bit_out <= std_logic_vector(Diff_Dec_DTConv_out1);

END rtl;

