-- -------------------------------------------------------------
-- 
-- File Name: D:\zizim\Documents\UJN_HW\proj2\hdl_prj\hdlsrc\dbpsk_hdl_cosim\dbpsk_hdl_cosim\DUT.vhd
-- Created: 2026-06-24 13:27:05
-- 
-- Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 1.5625e-05
-- Target subsystem base rate: 1.5625e-05
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        1.5625e-05
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- tx_mod_out                    ce_out        1.5625e-05
-- bits_out                      ce_out        1.5625e-05
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: DUT
-- Source Path: dbpsk_hdl_cosim/DUT
-- Hierarchy Level: 0
-- Model version: 1.12
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY DUT IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        bits_in                           :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        rx_sig_in                         :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        ce_out                            :   OUT   std_logic;
        tx_mod_out                        :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        bits_out                          :   OUT   std_logic_vector(7 DOWNTO 0)  -- uint8
        );
END DUT;


ARCHITECTURE rtl OF DUT IS

  -- Component Declarations
  COMPONENT DBPSK_Mod_HDL
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          bit_in                          :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
          sym_out                         :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En14
          );
  END COMPONENT;

  COMPONENT DBPSK_Demod_HDL
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          rx_sym_in                       :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          bit_out                         :   OUT   std_logic_vector(7 DOWNTO 0)  -- uint8
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : DBPSK_Mod_HDL
    USE ENTITY work.DBPSK_Mod_HDL(rtl);

  FOR ALL : DBPSK_Demod_HDL
    USE ENTITY work.DBPSK_Demod_HDL(rtl);

  -- Signals
  SIGNAL DBPSK_Mod_HDL_sym_out            : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL DBPSK_Demod_HDL_bit_out          : std_logic_vector(7 DOWNTO 0);  -- ufix8

BEGIN
  u_DBPSK_Mod_HDL : DBPSK_Mod_HDL
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              bit_in => bits_in,  -- uint8
              sym_out => DBPSK_Mod_HDL_sym_out  -- sfix16_En14
              );

  u_DBPSK_Demod_HDL : DBPSK_Demod_HDL
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              rx_sym_in => rx_sig_in,  -- sfix16_En14
              bit_out => DBPSK_Demod_HDL_bit_out  -- uint8
              );

  ce_out <= clk_enable;

  tx_mod_out <= DBPSK_Mod_HDL_sym_out;

  bits_out <= DBPSK_Demod_HDL_bit_out;

END rtl;

