// -------------------------------------------------------------
// 
// File Name: D:\zizim\Documents\UJN_HW\proj2\hdl_prj\hdlsrc\dbpsk_hdl_cosim\dbpsk_hdl_cosim\DUT.v
// Created: 2026-06-24 13:27:37
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 1.5625e-05
// Target subsystem base rate: 1.5625e-05
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ce_out        1.5625e-05
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// tx_mod_out                    ce_out        1.5625e-05
// bits_out                      ce_out        1.5625e-05
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: DUT
// Source Path: dbpsk_hdl_cosim/DUT
// Hierarchy Level: 0
// Model version: 1.12
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module DUT
          (clk,
           reset,
           clk_enable,
           bits_in,
           rx_sig_in,
           ce_out,
           tx_mod_out,
           bits_out);


  input   clk;
  input   reset;
  input   clk_enable;
  input   [7:0] bits_in;  // uint8
  input   signed [15:0] rx_sig_in;  // sfix16_En14
  output  ce_out;
  output  signed [15:0] tx_mod_out;  // sfix16_En14
  output  [7:0] bits_out;  // uint8


  wire signed [15:0] DBPSK_Mod_HDL_sym_out;  // sfix16_En14
  wire [7:0] DBPSK_Demod_HDL_bit_out;  // uint8


  DBPSK_Mod_HDL u_DBPSK_Mod_HDL (.clk(clk),
                                 .reset(reset),
                                 .enb(clk_enable),
                                 .bit_in(bits_in),  // uint8
                                 .sym_out(DBPSK_Mod_HDL_sym_out)  // sfix16_En14
                                 );

  assign tx_mod_out = DBPSK_Mod_HDL_sym_out;

  DBPSK_Demod_HDL u_DBPSK_Demod_HDL (.clk(clk),
                                     .reset(reset),
                                     .enb(clk_enable),
                                     .rx_sym_in(rx_sig_in),  // sfix16_En14
                                     .bit_out(DBPSK_Demod_HDL_bit_out)  // uint8
                                     );

  assign bits_out = DBPSK_Demod_HDL_bit_out;

  assign ce_out = clk_enable;

endmodule  // DUT

