-- -------------------------------------------------------------
-- 
-- File Name: D:\zizim\Documents\UJN_HW\proj2\hdl_prj\hdlsrc\dbpsk_hdl_cosim\dbpsk_hdl_cosim\DUT_pkg.vhd
-- Created: 2026-06-24 13:27:05
-- 
-- Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
-- 
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

PACKAGE DUT_pkg IS
  TYPE vector_of_signed16 IS ARRAY (NATURAL RANGE <>) OF signed(15 DOWNTO 0);
END DUT_pkg;

