-- -------------------------------------------------------------
-- 
-- File Name: D:\zizim\Documents\UJN_HW\proj2\hdl_prj\hdlsrc\voice_tx_hdl_cosim\voice_tx_hdl_cosim\BPSK_Demod_HDL.vhd
-- Created: 2026-06-22 19:14:49
-- 
-- Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: BPSK_Demod_HDL
-- Source Path: voice_tx_hdl_cosim/DUT/BPSK_Demod_HDL
-- Hierarchy Level: 1
-- Model version: 1.7
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY BPSK_Demod_HDL IS
  PORT( rx_sym_in                         :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        bit_out                           :   OUT   std_logic_vector(7 DOWNTO 0)  -- uint8
        );
END BPSK_Demod_HDL;


ARCHITECTURE rtl OF BPSK_Demod_HDL IS

  -- Component Declarations
  COMPONENT CmpZero
    PORT( u                               :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          y                               :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : CmpZero
    USE ENTITY work.CmpZero(rtl);

  -- Signals
  SIGNAL CmpZero_y                        : std_logic;
  SIGNAL DTConv_out1                      : unsigned(7 DOWNTO 0);  -- uint8

BEGIN
  u_CmpZero : CmpZero
    PORT MAP( u => rx_sym_in,  -- sfix16_En14
              y => CmpZero_y
              );

  DTConv_out1 <= '0' & '0' & '0' & '0' & '0' & '0' & '0' & CmpZero_y;

  bit_out <= std_logic_vector(DTConv_out1);

END rtl;

