-- -------------------------------------------------------------
-- 
-- File Name: D:\zizim\Documents\UJN_HW\proj2\hdl_prj\hdlsrc\voice_tx_hdl_cosim\voice_tx_hdl_cosim\DUT.vhd
-- Created: 2026-06-22 19:14:49
-- 
-- Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 0.000125
-- Target subsystem base rate: 0.01
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        0.01
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- tx_mod_out                    ce_out        0.01
-- bits_out                      ce_out        0.01
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: DUT
-- Source Path: voice_tx_hdl_cosim/DUT
-- Hierarchy Level: 0
-- Model version: 1.7
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY DUT IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        bits_in                           :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        rx_sig_in                         :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        ce_out                            :   OUT   std_logic;
        tx_mod_out                        :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        bits_out                          :   OUT   std_logic_vector(7 DOWNTO 0)  -- uint8
        );
END DUT;


ARCHITECTURE rtl OF DUT IS

  -- Component Declarations
  COMPONENT BPSK_Mod_HDL
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb_1_80_0                      :   IN    std_logic;
          bit_in                          :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
          sym_out                         :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En14
          );
  END COMPONENT;

  COMPONENT BPSK_Demod_HDL
    PORT( rx_sym_in                       :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          bit_out                         :   OUT   std_logic_vector(7 DOWNTO 0)  -- uint8
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : BPSK_Mod_HDL
    USE ENTITY work.BPSK_Mod_HDL(rtl);

  FOR ALL : BPSK_Demod_HDL
    USE ENTITY work.BPSK_Demod_HDL(rtl);

  -- Signals
  SIGNAL BPSK_Mod_HDL_sym_out             : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL BPSK_Demod_HDL_bit_out           : std_logic_vector(7 DOWNTO 0);  -- ufix8

BEGIN
  u_BPSK_Mod_HDL : BPSK_Mod_HDL
    PORT MAP( clk => clk,
              reset => reset,
              enb_1_80_0 => clk_enable,
              bit_in => bits_in,  -- uint8
              sym_out => BPSK_Mod_HDL_sym_out  -- sfix16_En14
              );

  u_BPSK_Demod_HDL : BPSK_Demod_HDL
    PORT MAP( rx_sym_in => rx_sig_in,  -- sfix16_En14
              bit_out => BPSK_Demod_HDL_bit_out  -- uint8
              );

  ce_out <= clk_enable;

  tx_mod_out <= BPSK_Mod_HDL_sym_out;

  bits_out <= BPSK_Demod_HDL_bit_out;

END rtl;

