// -------------------------------------------------------------
// 
// File Name: D:\zizim\Documents\UJN_HW\proj2\hdl_prj\hdlsrc\bpsk_hdl_cosim\bpsk_hdl_cosim\BPSK_Demod_HDL.v
// Created: 2026-06-22 19:17:35
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: BPSK_Demod_HDL
// Source Path: bpsk_hdl_cosim/DUT/BPSK_Demod_HDL
// Hierarchy Level: 1
// Model version: 1.11
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module BPSK_Demod_HDL
          (rx_sym_in,
           bit_out);


  input   signed [15:0] rx_sym_in;  // sfix16_En14
  output  [7:0] bit_out;  // uint8


  wire CmpZero_y;
  wire [7:0] DTConv_out1;  // uint8


  CmpZero u_CmpZero (.u(rx_sym_in),  // sfix16_En14
                     .y(CmpZero_y)
                     );

  assign DTConv_out1 = {7'b0, CmpZero_y};

  assign bit_out = DTConv_out1;

endmodule  // BPSK_Demod_HDL

