// -------------------------------------------------------------
// 
// File Name: D:\zizim\Documents\UJN_HW\proj2\hdl_prj\hdlsrc\bpsk_hdl_cosim\bpsk_hdl_cosim\BPSK_Mod_HDL.v
// Created: 2026-06-22 19:17:35
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: BPSK_Mod_HDL
// Source Path: bpsk_hdl_cosim/DUT/BPSK_Mod_HDL
// Hierarchy Level: 1
// Model version: 1.11
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module BPSK_Mod_HDL
          (clk,
           reset,
           enb,
           bit_in,
           sym_out);


  input   clk;
  input   reset;
  input   enb;
  input   [7:0] bit_in;  // uint8
  output  signed [15:0] sym_out;  // sfix16_En14


  wire init_guard_true_1;
  reg  init_guard_true_2;
  wire signed [15:0] outinit_guard_default;  // sfix16_En14
  wire relopout_1_1;
  wire prelookup_idx;  // ufix1
  wire signed [15:0] LUT_table_data [0:1];  // sfix16_En14 [2]
  wire signed [15:0] out;  // sfix16_En14
  reg signed [15:0] out_1;  // sfix16_En14
  wire signed [15:0] Delay_out1;  // sfix16_En14

  initial begin
    out_1 = 16'sb0000000000000000;
  end

  assign init_guard_true_1 = 1'b1;

  always @(posedge clk or posedge reset)
    begin : matching_delays_process
      if (reset == 1'b1) begin
        init_guard_true_2 <= 1'b0;
      end
      else begin
        if (enb) begin
          init_guard_true_2 <= init_guard_true_1;
        end
      end
    end

  assign outinit_guard_default = 16'sb0000000000000000;

  assign relopout_1_1 = bit_in >= 8'b00000001;

  assign prelookup_idx = relopout_1_1;

  assign LUT_table_data[0] = 16'sb0100000000000000;
  assign LUT_table_data[1] = 16'sb1100000000000000;
  assign out = LUT_table_data[prelookup_idx];

  always @(posedge clk)
    begin : PipelineRegister_process
      if (enb) begin
        out_1 <= out;
      end
    end

  assign Delay_out1 = (init_guard_true_2 == 1'b0 ? outinit_guard_default :
              out_1);

  assign sym_out = Delay_out1;

endmodule  // BPSK_Mod_HDL

