// -------------------------------------------------------------
// 
// File Name: D:\zizim\Documents\UJN_HW\proj2\hdl_prj\hdlsrc\bpsk_hdl_cosim\bpsk_hdl_cosim\CmpZero.v
// Created: 2026-06-22 19:17:35
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: CmpZero
// Source Path: bpsk_hdl_cosim/DUT/BPSK_Demod_HDL/CmpZero
// Hierarchy Level: 2
// Model version: 1.11
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module CmpZero
          (u,
           y);


  input   signed [15:0] u;  // sfix16_En14
  output  y;


  wire signed [15:0] Constant_out1;  // sfix16_En14
  wire Compare_out1;


  assign Constant_out1 = 16'sb0000000000000000;

  assign Compare_out1 = u < Constant_out1;

  assign y = Compare_out1;

endmodule  // CmpZero

